// <auto-generated />
using System;
using EasyBib.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyBib.Infrastructure.Migrations
{
    [DbContext(typeof(EasyBibDbContext))]
    [Migration("20261008125714_UpdatedSeed")]
    partial class UpdatedSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyBib.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("MembershipId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c50"),
                            DueDate = new DateOnly(2026, 10, 20),
                            MediaItemId = new Guid("21b8c7d6-5e4f-4a5b-c2d1-e0f9a8b7c6d5"),
                            MembershipId = new Guid("b2c3d4e5-6f7a-4b8c-9d0e-1f2a3b4c5d6e"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2b3c4d5e-6f7a-4b8c-9d0e-1f2a3b4c5d61"),
                            DueDate = new DateOnly(2026, 10, 27),
                            MediaItemId = new Guid("76a5b6c7-8d9e-4f0a-b7c6-d5e4f3a2b1c0"),
                            MembershipId = new Guid("e5f6a7b8-9c0d-4e1f-2a3b-4c5d6e7f8a9b"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3c4d5e6f-7a8b-4c9d-0e1f-2a3b4c5d6e72"),
                            DueDate = new DateOnly(2026, 10, 29),
                            MediaItemId = new Guid("a9d8e9f0-1a2b-4c3d-e4f3-a2b1c0d9e8f7"),
                            MembershipId = new Guid("d4e5f6a7-8b9c-4d0e-1f2a-3b4c5d6e7f8a"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("4d5e6f7a-8b9c-4d0e-1f2a-3b4c5d6e7f83"),
                            DueDate = new DateOnly(2026, 9, 29),
                            MediaItemId = new Guid("10a9b8c7-6d5e-4f4a-b3c2-d1e0f9a8b7c6"),
                            MembershipId = new Guid("a1b2c3d4-5e6f-4a7b-8c9d-0e1f2a3b4c5d"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("5e6f7a8b-9c0d-4e1f-2a3b-4c5d6e7f8a94"),
                            DueDate = new DateOnly(2026, 10, 4),
                            MediaItemId = new Guid("54e5f4a5-6b7c-4d8e-f9a8-b7c6d5e4f3a2"),
                            MembershipId = new Guid("f6a7b8c9-0d1e-4f2a-3b4c-5d6e7f8a9b0c"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("6f7a8b9c-0d1e-4f2a-3b4c-5d6e7f8a9ba5"),
                            DueDate = new DateOnly(2026, 9, 8),
                            MediaItemId = new Guid("43d6e5f4-5a6b-4c7d-e0f9-a8b7c6d5e4f3"),
                            MembershipId = new Guid("c3d4e5f6-7a8b-4c9d-0e1f-2a3b4c5d6e7f"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("7a8b9c0d-1e2f-4a3b-4c5d-6e7f8a9bac06"),
                            DueDate = new DateOnly(2026, 9, 22),
                            MediaItemId = new Guid("87b6c7d8-9e0f-4a1b-c6d5-e4f3a2b1c0d9"),
                            MembershipId = new Guid("b2c3d4e5-6f7a-4b8c-9d0e-1f2a3b4c5d6e"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8b9c0d1e-2f3a-4b4c-5d6e-7f8a9bacbd17"),
                            DueDate = new DateOnly(2026, 10, 6),
                            MediaItemId = new Guid("32c7d6e5-4f5a-4b6c-d1e0-f9a8b7c6d5e4"),
                            MembershipId = new Guid("e5f6a7b8-9c0d-4e1f-2a3b-4c5d6e7f8a9b"),
                            Status = 1
                        });
                });

            modelBuilder.Entity("EasyBib.Domain.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EAN")
                        .IsUnique();

                    b.ToTable("MediaItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10a9b8c7-6d5e-4f4a-b3c2-d1e0f9a8b7c6"),
                            EAN = "9783866812345",
                            Title = "Benders großes Kochbuch: 100 Rezepte mit Bier",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("21b8c7d6-5e4f-4a5b-c2d1-e0f9a8b7c6d5"),
                            EAN = "9783442378901",
                            Title = "Futurama: Die offizielle Enzyklopädie des 31. Jahrhunderts",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("32c7d6e5-4f5a-4b6c-d1e0-f9a8b7c6d5e4"),
                            EAN = "9783551312456",
                            Title = "Was oper, Doc? – Die große Looney-Tunes-Chronik",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("43d6e5f4-5a6b-4c7d-e0f9-a8b7c6d5e4f3"),
                            EAN = "5051892345678",
                            Title = "Falsches Spiel mit Roger Rabbit",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("54e5f4a5-6b7c-4d8e-f9a8-b7c6d5e4f3a2"),
                            EAN = "8839295674012",
                            Title = "Space Jam",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("65f4a5b6-7c8d-4e9f-a8b7-c6d5e4f3a2b1"),
                            EAN = "7321950286734",
                            Title = "Looney Tunes: Back in Action",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("76a5b6c7-8d9e-4f0a-b7c6-d5e4f3a2b1c0"),
                            EAN = "5030930124567",
                            Title = "Looney Tunes: Acme Arsenal",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("87b6c7d8-9e0f-4a1b-c6d5-e4f3a2b1c0d9"),
                            EAN = "5035229098765",
                            Title = "Futurama: Das Videospiel",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("98c7d8e9-0f1a-4b2c-d5e4-f3a2b1c0d9e8"),
                            EAN = "4035229112233",
                            Title = "Looney Tunes: World of Mayhem",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a9d8e9f0-1a2b-4c3d-e4f3-a2b1c0d9e8f7"),
                            EAN = "8839295674321",
                            Title = "Futurama: Benders großer Coup",
                            Type = 2
                        });
                });

            modelBuilder.Entity("EasyBib.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2a1b9c-6d4e-4a7c-9f10-1e2d3c4b5a69"),
                            Email = "philip.fry@planetexpress.de",
                            Name = "Philip J. Fry"
                        },
                        new
                        {
                            Id = new Guid("8c1d4e7a-2b3f-4c8d-a9e0-5f6a7b8c9d01"),
                            Email = "turanga.leela@planetexpress.de",
                            Name = "Turanga Leela"
                        },
                        new
                        {
                            Id = new Guid("b7e8f9a0-1c2d-4e3f-b5a6-79804d1e2f30"),
                            Email = "professor@farnsworth-labor.de",
                            Name = "Hubert J. Farnsworth"
                        },
                        new
                        {
                            Id = new Guid("d4c3b2a1-0f9e-4d8c-b7a6-5e4f3d2c1b0a"),
                            Email = "amy.wong@wong-industrien.de",
                            Name = "Amy Wong"
                        },
                        new
                        {
                            Id = new Guid("e5d4c3b2-1a09-4f8e-c7d6-a5b4c3d2e1f0"),
                            Email = "bugs.bunny@looney-tunes.de",
                            Name = "Bugs Bunny"
                        },
                        new
                        {
                            Id = new Guid("f6e5d4c3-2b1a-4a9d-d8c7-b6a5f4e3d2c1"),
                            Email = "daffy.duck@looney-tunes.de",
                            Name = "Daffy Duck"
                        });
                });

            modelBuilder.Entity("EasyBib.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LoanPeriodDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxActiveLoans")
                        .HasColumnType("int");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlanName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-5e6f-4a7b-8c9d-0e1f2a3b4c5d"),
                            LoanPeriodDays = 14,
                            MaxActiveLoans = 2,
                            MemberId = new Guid("3f2a1b9c-6d4e-4a7c-9f10-1e2d3c4b5a69"),
                            PlanName = 0
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-6f7a-4b8c-9d0e-1f2a3b4c5d6e"),
                            LoanPeriodDays = 28,
                            MaxActiveLoans = 5,
                            MemberId = new Guid("8c1d4e7a-2b3f-4c8d-a9e0-5f6a7b8c9d01"),
                            PlanName = 2
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-7a8b-4c9d-0e1f-2a3b4c5d6e7f"),
                            LoanPeriodDays = 14,
                            MaxActiveLoans = 2,
                            MemberId = new Guid("b7e8f9a0-1c2d-4e3f-b5a6-79804d1e2f30"),
                            PlanName = 0
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-8b9c-4d0e-1f2a-3b4c5d6e7f8a"),
                            LoanPeriodDays = 21,
                            MaxActiveLoans = 8,
                            MemberId = new Guid("d4c3b2a1-0f9e-4d8c-b7a6-5e4f3d2c1b0a"),
                            PlanName = 1
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-9c0d-4e1f-2a3b-4c5d6e7f8a9b"),
                            LoanPeriodDays = 21,
                            MaxActiveLoans = 8,
                            MemberId = new Guid("e5d4c3b2-1a09-4f8e-c7d6-a5b4c3d2e1f0"),
                            PlanName = 1
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0d1e-4f2a-3b4c-5d6e7f8a9b0c"),
                            LoanPeriodDays = 28,
                            MaxActiveLoans = 5,
                            MemberId = new Guid("f6e5d4c3-2b1a-4a9d-d8c7-b6a5f4e3d2c1"),
                            PlanName = 2
                        });
                });

            modelBuilder.Entity("EasyBib.Domain.Entities.Loan", b =>
                {
                    b.HasOne("EasyBib.Domain.Entities.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyBib.Domain.Entities.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("EasyBib.Domain.Entities.Membership", b =>
                {
                    b.HasOne("EasyBib.Domain.Entities.Member", "Member")
                        .WithOne("Membership")
                        .HasForeignKey("EasyBib.Domain.Entities.Membership", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("EasyBib.Domain.Entities.Member", b =>
                {
                    b.Navigation("Membership");
                });
#pragma warning restore 612, 618
        }
    }
}
